// Dummy data
export const tradesData = [
  {
    srNo: 1,
    date: "2026-01-10",
    currency: "SOLUSDT",
    quantity: 200,
    timeFrame: "5m",
    typeOfTrade: "Scalping",
    tradingStrategy: "-",
    longShort: "Long",
    winLoss: "Loss",
    profitLoss: -12.0,
    balance: 84382.0,
  },
  {
    srNo: 2,
    date: "2026-01-12",
    currency: "BTCUSDT",
    quantity: 1,
    timeFrame: "15m",
    typeOfTrade: "Position",
    tradingStrategy: "-",
    longShort: "Short",
    winLoss: "Loss",
    profitLoss: -103.06,
    balance: 84278.94,
  },
  {
    srNo: 3,
    date: "2026-01-12",
    currency: "BTCUSDT",
    quantity: 1,
    timeFrame: "1m",
    typeOfTrade: "Scalping",
    tradingStrategy: "Order block",
    longShort: "Short",
    winLoss: "Loss",
    profitLoss: -23.75,
    balance: 84255.19,
  },
  {
    srNo: 4,
    date: "2026-01-13",
    currency: "BTCUSDT",
    quantity: 1,
    timeFrame: "1m",
    typeOfTrade: "Scalping",
    tradingStrategy: "15&9 EMA",
    longShort: "Short",
    winLoss: "Win",
    profitLoss: 37.57,
    balance: 84292.76,
  },
  {
    srNo: 5,
    date: "2026-01-14",
    currency: "ETHUSDT",
    quantity: 5,
    timeFrame: "5m",
    typeOfTrade: "Scalping",
    tradingStrategy: "Breakout",
    longShort: "Long",
    winLoss: "Win",
    profitLoss: 125.4,
    balance: 84418.16,
  },
  {
    srNo: 6,
    date: "2026-01-15",
    currency: "SOLUSDT",
    quantity: 300,
    timeFrame: "1m",
    typeOfTrade: "Scalping",
    tradingStrategy: "VWAP",
    longShort: "Long",
    winLoss: "Win",
    profitLoss: 62.75,
    balance: 84480.91,
  },
  {
    srNo: 7,
    date: "2026-01-16",
    currency: "BNBUSDT",
    quantity: 3,
    timeFrame: "30m",
    typeOfTrade: "Swing",
    tradingStrategy: "Support & Resistance",
    longShort: "Long",
    winLoss: "Loss",
    profitLoss: -89.3,
    balance: 84391.61,
  },
  {
    srNo: 8,
    date: "2025-12-13",
    currency: "BTCUSDT",
    quantity: 10,
    timeFrame: "1m",
    typeOfTrade: "Scalping",
    tradingStrategy: "15&9 EMA",
    longShort: "Short",
    winLoss: "Win",
    profitLoss: 1988.0,
    balance: 86379.61,
  },
  {
    srNo: 9,
    date: "2025-12-14",
    currency: "ETHUSDT",
    quantity: 8,
    timeFrame: "4h",
    typeOfTrade: "Swing",
    tradingStrategy: "Trendline",
    longShort: "Long",
    winLoss: "Win",
    profitLoss: 540.0,
    balance: 86919.61,
  },
  {
    srNo: 10,
    date: "2025-12-15",
    currency: "XRPUSDT",
    quantity: 1000,
    timeFrame: "1h",
    typeOfTrade: "Position",
    tradingStrategy: "Breakout",
    longShort: "Long",
    winLoss: "Loss",
    profitLoss: -210.5,
    balance: 86709.11,
  },
  {
    srNo: 11,
    date: "2026-01-18",
    currency: "ADAUSDT",
    quantity: 1500,
    timeFrame: "15m",
    typeOfTrade: "Scalping",
    tradingStrategy: "RSI Divergence",
    longShort: "Long",
    winLoss: "Win",
    profitLoss: 312.45,
    balance: 87021.56,
  },
  {
    srNo: 12,
    date: "2026-01-20",
    currency: "BTCUSDT",
    quantity: 0.75,
    timeFrame: "1h",
    typeOfTrade: "Position",
    tradingStrategy: "Breakout",
    longShort: "Short",
    winLoss: "Loss",
    profitLoss: -450.0,
    balance: 86571.56,
  },
  {
    srNo: 13,
    date: "2026-02-02",
    currency: "BTCUSDT",
    quantity: 0.8,
    timeFrame: "15m",
    typeOfTrade: "Scalping",
    tradingStrategy: "15&9 EMA",
    longShort: "Long",
    winLoss: "Win",
    profitLoss: 145.32,
    balance: 86756.35,
  },
  {
    srNo: 14,
    date: "2026-02-05",
    currency: "ETHUSDT",
    quantity: 6,
    timeFrame: "5m",
    typeOfTrade: "Scalping",
    tradingStrategy: "VWAP",
    longShort: "Short",
    winLoss: "Loss",
    profitLoss: -82.45,
    balance: 86673.90,
  },
  {
    srNo: 15,
    date: "2026-02-08",
    currency: "SOLUSDT",
    quantity: 500,
    timeFrame: "1m",
    typeOfTrade: "Scalping",
    tradingStrategy: "Breakout",
    longShort: "Long",
    winLoss: "Win",
    profitLoss: 96.8,
    balance: 86770.70,
  },
  {
    srNo: 16,
    date: "2026-02-14",
    currency: "BNBUSDT",
    quantity: 4,
    timeFrame: "30m",
    typeOfTrade: "Swing",
    tradingStrategy: "Support & Resistance",
    longShort: "Short",
    winLoss: "Loss",
    profitLoss: -210.15,
    balance: 86560.55,
  },
  {
    srNo: 17,
    date: "2026-02-20",
    currency: "BTCUSDT",
    quantity: 1.2,
    timeFrame: "1h",
    typeOfTrade: "Position",
    tradingStrategy: "Order block",
    longShort: "Long",
    winLoss: "Win",
    profitLoss: 325.40,
    balance: 86885.95,
  }
];


// Column configuration
export const columnConfig = [
  {
    dataField: "srNo",
    caption: "Sr NO",
    dataType: "number",
    visible: true,
    alignment: "left",
  },
  {
    dataField: "date",
    caption: "Date",
    dataType: "date",
    format: "dd-MM-yyyy",
    visible: true,
    alignment: "left",
  },
  {
    dataField: "currency",
    caption: "Currency",
    dataType: "string",
    visible: true,
    alignment: "left",
  },
  {
    dataField: "quantity",
    caption: "Quantity",
    dataType: "number",
    visible: true,
    alignment: "left",
  },
  {
    dataField: "timeFrame",
    caption: "Time Frame",
    dataType: "string",
    visible: true,
    alignment: "left",
  },
  {
    dataField: "typeOfTrade",
    caption: "Type of Trade",
    dataType: "string",
    visible: true,
    alignment: "left",
  },
  {
    dataField: "tradingStrategy",
    caption: "Trading Strategy",
    dataType: "string",
    visible: true,
    alignment: "left",
  },
  {
    dataField: "longShort",
    caption: "Long / Short",
    dataType: "string",
    visible: true,
    alignment: "left",
  },
  {
    dataField: "winLoss",
    caption: "Win / Loss",
    dataType: "string",
    visible: true,
    alignment: "left",
  },
  {
    dataField: "profitLoss",
    caption: "Profit / Loss ($)",
    dataType: "number",
    visible: true,
    alignment: "left",
    format: {
      type: "fixedPoint",
      precision: 2,
    },
  },
  {
    dataField: "balance",
    caption: "Balance ($)",
    dataType: "number",
    visible: true,
    alignment: "left",
    format: {
      type: "fixedPoint",
      precision: 2,
    },
  },
];


// export { tradingData, columnConfig };
